### ISSUE TITLE
USD-Seg on MM-detection Issue Tracker

### ISSUE THREAD

**Issue by ElectronicElephant** [YoruCathy/USDSeg-FCOS#1]
- [x] https://github.com/YoruCathy/usd_seg/commit/ca2b6c4e4a7fe9d5680ddc4a2f2e33e724dc3758#r37498761

- [x] https://github.com/YoruCathy/usd_seg/commit/ca2b6c4e4a7fe9d5680ddc4a2f2e33e724dc3758#r37499831

- [x] Use cv2 / mmcv to resize images

- [ ] always use `--no-ff` option to merge
